name: gerar-keystore
on: workflow_dispatch
jobs:
  gerar:
    runs-on: ubuntu-latest
    steps:
      - name: Criar keystore
        run: keytool -genkeypair -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000
      - name: Converter pra base64
        run: base64 -w 0 debug.keystore > debug.keystore.b64
      - name: Mostrar resultado
        run: cat debug.keystore.b64
